### ISSUE TITLE
一些前端必读的资料

### ISSUE THREAD

**Issue by pftom** [tuture-dev/daily#10]
必读的 JS talk：https://github.com/AllThingsSmitty/must-watch-javascript
30 seconds of code：https://github.com/30-seconds/30-seconds-of-code
前端性能优化清单：https://github.com/thedaviddias/Front-End-Performance-Checklist
every-programmer-need-know：https://github.com/mtdvio/every-programmer-should-know
动手完成一个最小的编译器：https://github.com/jamiebuilds/the-super-tiny-compiler
JavaScript 算法和数据结构：https://github.com/trekhleb/javascript-algorithms
互联网技术公司架构：https://github.com/davideuler/architecture.of.internet-product

**Comment by mrcfps** [comment]
已全部发布
