### ISSUE TITLE
【热点】Node.js 正式推出 14.0.0 版本

### ISSUE THREAD

**Issue by mrcfps** [tuture-dev/daily#2]
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.0.0

**Comment by pftom** [comment]
强无敌

**Comment by mrcfps** [comment]
- 诊断报告功能进入稳定状态
- V8 升级到 8.1 版本，支持 Optional Chaining、Nullish Coalescing 等新语法
- 引入试验性的异步 Local Storage API
- 引入试验性的 Web Assembly 接口

Quoted from https://medium.com/@nodejs/node-js-version-14-available-now-8170d384567e.
